# Generated by Django 4.2.7 on 2023-12-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0002_posts_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="tags",
        ),
        migrations.AddField(
            model_name="posts",
            name="tags",
            field=models.ManyToManyField(
                default=None, to="Blog.tags", verbose_name="Теги"
            ),
        ),
    ]
